export const WORLD_SUBSECTIONS = [
  { key: 'america',    label: 'अमेरिका',        labelEn: 'America',       emoji: '🇺🇸', color: '#1D4ED8', row: 1,
    keywords: ['america', 'usa', 'अमेरिका', 'trump', 'biden', 'washington', 'white house', 'congress', 'pentagon'] },
  { key: 'china',      label: 'चीन',             labelEn: 'China',         emoji: '🇨🇳', color: '#DC2626', row: 1,
    keywords: ['china', 'चीन', 'beijing', 'xi jinping', 'taiwan', 'ताइवान', 'hong kong', 'पीएलए'] },
  { key: 'pakistan',   label: 'पाकिस्तान',       labelEn: 'Pakistan',      emoji: '🇵🇰', color: '#16A34A', row: 1,
    keywords: ['pakistan', 'पाकिस्तान', 'islamabad', 'lahore', 'karachi', 'imran', 'nawaz', 'शहबाज', 'आईएसआई'] },
  { key: 'russia',     label: 'रूस-यूक्रेन',    labelEn: 'Russia-Ukraine', emoji: '🇷🇺', color: '#7C3AED', row: 1,
    keywords: ['russia', 'रूस', 'ukraine', 'यूक्रेन', 'putin', 'पुतिन', 'zelensky', 'क्रेमलिन', 'moscow', 'kyiv'] },
  { key: 'middleeast', label: 'मध्य पूर्व',      labelEn: 'Middle East',   emoji: '🕌', color: '#D97706', row: 2,
    keywords: ['israel', 'इजरायल', 'gaza', 'गाज़ा', 'iran', 'ईरान', 'middle east', 'मध्य पूर्व', 'saudi', 'सऊदी', 'हमास', 'hamas', 'hezbollah'] },
  { key: 'europe',     label: 'यूरोप',           labelEn: 'Europe',        emoji: '🇪🇺', color: '#0891B2', row: 2,
    keywords: ['europe', 'यूरोप', 'france', 'फ्रांस', 'germany', 'जर्मनी', 'uk', 'britain', 'ब्रिटेन', 'eu', 'nato', 'london', 'paris', 'berlin'] },
  { key: 'southasia',  label: 'दक्षिण एशिया',   labelEn: 'South Asia',    emoji: '🌏', color: '#059669', row: 2,
    keywords: ['nepal', 'नेपाल', 'bangladesh', 'बांग्लादेश', 'sri lanka', 'श्रीलंका', 'myanmar', 'myanmar', 'afghanistan', 'अफगानिस्तान', 'maldives', 'मालदीव'] },
  { key: 'un',         label: 'संयुक्त राष्ट्र', labelEn: 'UN & Global',   emoji: '🌐', color: '#1E40AF', row: 2,
    keywords: ['united nations', 'संयुक्त राष्ट्र', 'un ', 'nato', 'imf', 'world bank', 'g20', 'g7', 'who', 'विश्व स्वास्थ्य'] },
  { key: 'climate',    label: 'जलवायु परिवर्तन', labelEn: 'Climate',       emoji: '🌍', color: '#16A34A', row: 3,
    keywords: ['climate', 'जलवायु', 'global warming', 'ग्लोबल वार्मिंग', 'environment', 'पर्यावरण', 'cop', 'carbon', 'flood', 'earthquake', 'tsunami'] },
  { key: 'economy',    label: 'वैश्विक अर्थव्यवस्था', labelEn: 'Global Economy', emoji: '📈', color: '#D97706', row: 3,
    keywords: ['global economy', 'वैश्विक अर्थव्यवस्था', 'oil price', 'तेल', 'dollar', 'डॉलर', 'recession', 'मंदी', 'trade war', 'imf', 'world bank'] },
  { key: 'worldtech',  label: 'विज्ञान-तकनीक',  labelEn: 'Science & Tech', emoji: '🚀', color: '#6D28D9', row: 3,
    keywords: ['nasa', 'space', 'अंतरिक्ष', 'spacex', 'elon musk', 'ai ', 'artificial intelligence', 'quantum', 'mars', 'moon mission'] },
];
